apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
     app: hello

spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello

  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: hello
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1