apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
  labels:
    app: hello
spec:
  selector:
    app: hello

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer